### ISSUE TITLE
The script gives the following error?

### ISSUE THREAD

**Issue by rashid22222** [pointwise/AircraftMesher#1]
Warning: dom-3: Could not initialize domain in quilt mode. 374 inverted faces in 2D. (MeshFace is inverted)
Warning: dom-3: Could not initialize domain in quilt mode. (MeshFace is inverted)
Warning: dom-13: Could not initialize domain in quilt mode. 1 inverted faces in 2D. (MeshFace is inverted)
Warning: dom-13: Could not initialize domain in quilt mode. (MeshFace is inverted)
Warning: dom-13: Seed mesh contains folds in 3D.
Warning: dom-13: Mesh boundary triangulation failed during domain initialization. Check dom-13.
Error: dom-13: ERROR: Domain initialization failed
Warning: dom-13: Mesh boundary triangulation failed during the last action. Check dom-13.
Script: Resolved Curvature at Wing/Empennage Leading & Trailing Edges
Script: Surface Meshing Complete
Script: ----- TCL TRACE -----
Script: invalid command name ""
Script:     while executing
Script: "$ffBlk setName "aniso-blk""
Script:     (file "C:\Users\Rashid\Desktop\AircraftMesher-master\AircraftMesher.glf" line 667)
Script: ---------------------
Info: Script C:\Users\Aero\Desktop\AircraftMesher-master\AircraftMesher.glf failed.

**Comment by pabakertx** [comment]
The script is failing at the indicated location because the earlier failure of the domains to initialize. The warnings indicate a problem that most likely originates with the geometry. The best we could do to 'fix' this issue is to exit the script when a domain initialization or block assembly step fails. We wouldn't be able to diagnose this any further without the geometry file. Please contact customer support to help troubleshoot this further: support@pointwise.com.

**Comment by AOE-khkhan** [comment]
The geometry file is given in pointwise as .pw file. So why it can not be fixed yet?

**Comment by pabakertx** [comment]
> The geometry file is given in pointwise as .pw file. So why it can not be fixed yet?

I'm not sure what you're asking. What geometry file are you referring to, the example file in the repository? What needs to be fixed? Have you contacted customer support with your issue yet (support@pointwise.com)?

We're not actively maintaining this script, as the latest versions of Fidelity Pointwise have an automatic surface meshing feature that will work much more robustly than this script. If you're on active maintenance, you should check out this feature and any of the tutorial videos available on YouTube.
